#
# step 1: kubectl create namespace jenkins
# step 2: kubectl create -f <this file>
# step 3: kubectl exec <podname> --namespace jenkins -- cat /var/lib/jenkins/secrets/initialAdminPassword
#
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins-container
          image: jenkins
          ports:
            - containerPort: 8080
